#!/usr/bin/env bash
# -*- coding: utf-8; mode: sh -*-
# ----------------------------------------------------------------------------
# wrapper to start python scripts within sphkerneldoc environment
# ----------------------------------------------------------------------------

source $(dirname ${BASH_SOURCE[0]})/setup.sh

export PATH="${SCRIPT_FOLDER}:${PATH}"


export REPO_ROOT
export CACHE
export SCRIPT_FOLDER
export TEMPLATES

export DOC_FOLDER
export AUTODOC_FOLDER
export BOOKS_FOLDER
export LINUX_MISC_DOC

export LINUX_SRC_TREE
export LINUX_DOCBOOK_ROOT

export KERNEL_DOC_SCRIPT

dbtools.py ${*}
